
#define ALPHA 0.001
#define EPOCH 20
#define REGULARIZATION L2
#define LAMBDA 0.01
#define CLIENTNODES 3
// #define PERCENTUALTRAINING 120 / CLIENTNODES;
#define PERCENTUALTRAINING 40
#define INTERCATIONCYCLE 10
